# Generated by Django 4.2.16 on 2025-06-08 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_timetable_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='enrolled_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program'),
        ),
    ]
