# Generated by Django 5.1.3 on 2025-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="semester",
            field=models.CharField(
                blank=True,
                choices=[("Semester 1", "Semester 1"), ("Semester 2", "Semester 2")],
                max_length=20,
                null=True,
            ),
        ),
    ]
