# Generated by Django 4.2.16 on 2025-06-05 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(default=django.utils.timezone.now, help_text='Enter full Admission/Staff number e.g. P100/1681gG/21', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
