# Generated by Django 4.2.16 on 2025-06-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.CharField(help_text='Enter full Admission Number e.g. P100/1681/21', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student')], default='student', max_length=20),
        ),
    ]
